"""PlatformIO pre-build hook: embed web/index.html into the firmware.

Reads ../web/index.html, gzips it, and writes src/web_asset.h as a byte array.
Running this on every build means a change to the UI is picked up by a plain
`pio run` with no extra step to forget.
"""
import gzip
import os
import pathlib

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

HERE = pathlib.Path(env.subst("$PROJECT_DIR"))  # noqa: F821
SOURCE = HERE.parent / "web" / "index.html"
TARGET = HERE / "src" / "web_asset.h"


def build_header() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"Zephyr: web UI not found at {SOURCE}")

    raw = SOURCE.read_bytes()
    # mtime=0 so identical input produces an identical header -> no needless
    # rebuilds and reproducible binaries.
    packed = gzip.compress(raw, compresslevel=9, mtime=0)

    lines = [
        "// Generated by tools/build_web.py -- do not edit by hand.",
        f"// Source: web/index.html ({len(raw)} bytes -> {len(packed)} gzipped)",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"static const uint32_t kWebAssetRawSize = {len(raw)};",
        f"static const uint32_t kWebAssetGzipSize = {len(packed)};",
        "static const uint8_t kWebAssetGzip[] PROGMEM = {",
    ]
    for i in range(0, len(packed), 16):
        chunk = packed[i : i + 16]
        lines.append("    " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())
    lines.append("};")
    lines.append("")

    header = "\n".join(lines)
    # Only rewrite when the content actually changed, to keep ccache/SCons happy.
    if TARGET.exists() and TARGET.read_text() == header:
        return
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(header)
    print(f"Zephyr: embedded web UI  {len(raw)} B -> {len(packed)} B gzipped")


build_header()
